# Generated by Django 4.1.7 on 2023-02-22 16:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_created_note_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='notes',
            field=tinymce.models.HTMLField(),
        ),
    ]
