# Generated by Django 4.1.7 on 2023-02-22 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='notes',
            new_name='content',
        ),
    ]
